namespace StudentApp_Controller.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ExtendFieldLengths : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Admins", "UserEmail", "dbo.Users");
            DropForeignKey("dbo.Metadatas", "UserId", "dbo.Users");
            DropForeignKey("dbo.Students", "UserEmail", "dbo.Users");
            DropForeignKey("dbo.Teachers", "UserEmail", "dbo.Users");
            DropForeignKey("dbo.StudentUnitGrades", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.Invoices", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, "dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges");
            DropForeignKey("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", "dbo.Teachers");
            DropForeignKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" }, "dbo.RegisterStudentInSemesterAtColleges");
            DropIndex("dbo.Admins", new[] { "UserEmail" });
            DropIndex("dbo.Metadatas", new[] { "UserId" });
            DropIndex("dbo.Students", new[] { "UserEmail" });
            DropIndex("dbo.Invoices", new[] { "StudentEmail" });
            DropIndex("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            DropIndex("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" });
            DropIndex("dbo.StudentUnitGrades", new[] { "StudentEmail" });
            DropIndex("dbo.SubjectInCourseAtSemesterAtColleges", new[] { "TeacherEmail" });
            DropIndex("dbo.Teachers", new[] { "UserEmail" });
            DropIndex("dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail" });
            DropPrimaryKey("dbo.Admins");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Students");
            DropPrimaryKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges");
            DropPrimaryKey("dbo.StudentUnitGrades");
            DropPrimaryKey("dbo.Teachers");
            DropPrimaryKey("dbo.RegisterStudentInSemesterAtColleges");
            AlterColumn("dbo.Admins", "UserEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Users", "Email", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Users", "FirstName", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Users", "LastName", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Users", "Address", c => c.String(nullable: false, maxLength: 256, unicode: false));
            AlterColumn("dbo.Users", "City", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Users", "Gender", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Metadatas", "UserId", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Students", "UserEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Invoices", "StudentEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Invoices", "EnroledStudentEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Invoices", "Misc", c => c.String(nullable: false, maxLength: 512, unicode: false));
            AlterColumn("dbo.Receipts", "Misc", c => c.String(nullable: false, maxLength: 512, unicode: false));
            AlterColumn("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", "StudentEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.StudentUnitGrades", "StudentEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Subjects", "Name", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.Teachers", "UserEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AlterColumn("dbo.Colleges", "Name", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.Colleges", "Address", c => c.String(nullable: false, maxLength: 256, unicode: false));
            AlterColumn("dbo.Colleges", "City", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", c => c.String(nullable: false, maxLength: 320, unicode: false));
            AddPrimaryKey("dbo.Admins", "UserEmail");
            AddPrimaryKey("dbo.Users", "Email");
            AddPrimaryKey("dbo.Students", "UserEmail");
            AddPrimaryKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            AddPrimaryKey("dbo.StudentUnitGrades", new[] { "StudentEmail", "UnitCode", "SubjectId", "CourseCode", "Year", "SecondSemester", "CollegeId" });
            AddPrimaryKey("dbo.Teachers", "UserEmail");
            AddPrimaryKey("dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail", "Year", "SecondSemester", "CollegeId" });
            CreateIndex("dbo.Admins", "UserEmail");
            CreateIndex("dbo.Metadatas", "UserId");
            CreateIndex("dbo.Students", "UserEmail");
            CreateIndex("dbo.Invoices", "StudentEmail");
            CreateIndex("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            CreateIndex("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" });
            CreateIndex("dbo.StudentUnitGrades", "StudentEmail");
            CreateIndex("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail");
            CreateIndex("dbo.Teachers", "UserEmail");
            CreateIndex("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail");
            AddForeignKey("dbo.Admins", "UserEmail", "dbo.Users", "Email");
            AddForeignKey("dbo.Metadatas", "UserId", "dbo.Users", "Email", cascadeDelete: true);
            AddForeignKey("dbo.Students", "UserEmail", "dbo.Users", "Email");
            AddForeignKey("dbo.Teachers", "UserEmail", "dbo.Users", "Email");
            AddForeignKey("dbo.StudentUnitGrades", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.Invoices", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, "dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, cascadeDelete: true);
            AddForeignKey("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", "dbo.Teachers", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" }, "dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail", "Year", "SecondSemester", "CollegeId" });
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" }, "dbo.RegisterStudentInSemesterAtColleges");
            DropForeignKey("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", "dbo.Teachers");
            DropForeignKey("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, "dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges");
            DropForeignKey("dbo.Invoices", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.StudentUnitGrades", "StudentEmail", "dbo.Students");
            DropForeignKey("dbo.Teachers", "UserEmail", "dbo.Users");
            DropForeignKey("dbo.Students", "UserEmail", "dbo.Users");
            DropForeignKey("dbo.Metadatas", "UserId", "dbo.Users");
            DropForeignKey("dbo.Admins", "UserEmail", "dbo.Users");
            DropIndex("dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail" });
            DropIndex("dbo.Teachers", new[] { "UserEmail" });
            DropIndex("dbo.SubjectInCourseAtSemesterAtColleges", new[] { "TeacherEmail" });
            DropIndex("dbo.StudentUnitGrades", new[] { "StudentEmail" });
            DropIndex("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" });
            DropIndex("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            DropIndex("dbo.Invoices", new[] { "StudentEmail" });
            DropIndex("dbo.Students", new[] { "UserEmail" });
            DropIndex("dbo.Metadatas", new[] { "UserId" });
            DropIndex("dbo.Admins", new[] { "UserEmail" });
            DropPrimaryKey("dbo.RegisterStudentInSemesterAtColleges");
            DropPrimaryKey("dbo.Teachers");
            DropPrimaryKey("dbo.StudentUnitGrades");
            DropPrimaryKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges");
            DropPrimaryKey("dbo.Students");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Admins");
            AlterColumn("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Colleges", "City", c => c.String(nullable: false, maxLength: 16, unicode: false));
            AlterColumn("dbo.Colleges", "Address", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.Colleges", "Name", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.Teachers", "UserEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Subjects", "Name", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.StudentUnitGrades", "StudentEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", "StudentEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Receipts", "Misc", c => c.String(nullable: false, maxLength: 256, unicode: false));
            AlterColumn("dbo.Invoices", "Misc", c => c.String(nullable: false, maxLength: 256, unicode: false));
            AlterColumn("dbo.Invoices", "EnroledStudentEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Invoices", "StudentEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Students", "UserEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Metadatas", "UserId", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Users", "Gender", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.Users", "City", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.Users", "Address", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.Users", "LastName", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.Users", "FirstName", c => c.String(nullable: false, maxLength: 32, unicode: false));
            AlterColumn("dbo.Users", "Email", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AlterColumn("dbo.Admins", "UserEmail", c => c.String(nullable: false, maxLength: 64, unicode: false));
            AddPrimaryKey("dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail", "Year", "SecondSemester", "CollegeId" });
            AddPrimaryKey("dbo.Teachers", "UserEmail");
            AddPrimaryKey("dbo.StudentUnitGrades", new[] { "StudentEmail", "UnitCode", "SubjectId", "CourseCode", "Year", "SecondSemester", "CollegeId" });
            AddPrimaryKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            AddPrimaryKey("dbo.Students", "UserEmail");
            AddPrimaryKey("dbo.Users", "Email");
            AddPrimaryKey("dbo.Admins", "UserEmail");
            CreateIndex("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail");
            CreateIndex("dbo.Teachers", "UserEmail");
            CreateIndex("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail");
            CreateIndex("dbo.StudentUnitGrades", "StudentEmail");
            CreateIndex("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" });
            CreateIndex("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" });
            CreateIndex("dbo.Invoices", "StudentEmail");
            CreateIndex("dbo.Students", "UserEmail");
            CreateIndex("dbo.Metadatas", "UserId");
            CreateIndex("dbo.Admins", "UserEmail");
            AddForeignKey("dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId" }, "dbo.RegisterStudentInSemesterAtColleges", new[] { "StudentEmail", "Year", "SecondSemester", "CollegeId" });
            AddForeignKey("dbo.SubjectInCourseAtSemesterAtColleges", "TeacherEmail", "dbo.Teachers", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.Invoices", new[] { "EnroledStudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, "dbo.RegisteredStudentEnrolInCourseAtSemesterAtColleges", new[] { "StudentEmail", "StudentYear", "StudentSecondSemester", "StudentCollegeId", "CourseCode", "CourseYear", "CourseSecondSemester", "CourseCollegeId" }, cascadeDelete: true);
            AddForeignKey("dbo.Invoices", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.RegisterStudentInSemesterAtColleges", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.StudentUnitGrades", "StudentEmail", "dbo.Students", "UserEmail", cascadeDelete: true);
            AddForeignKey("dbo.Teachers", "UserEmail", "dbo.Users", "Email");
            AddForeignKey("dbo.Students", "UserEmail", "dbo.Users", "Email");
            AddForeignKey("dbo.Metadatas", "UserId", "dbo.Users", "Email", cascadeDelete: true);
            AddForeignKey("dbo.Admins", "UserEmail", "dbo.Users", "Email");
        }
    }
}
